// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomacaoCuponagem.Features.PortalCuponagem
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Cuponagem_Alterar Dados do EC")]
    public partial class Cuponagem_AlterarDadosDoECFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AlterarDadosEC.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Cuponagem_Alterar Dados do EC", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1- Validar_Acesso_Alteração_do_EC(Via URL)")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _1_Validar_Acesso_Alteracao_Do_ECViaURL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1- Validar_Acesso_Alteração_do_EC(Via URL)", new string[] {
                        "web"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("que faço o login com EC Com Cadastro do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 7
 testRunner.When("acesso a tela de Alteração de Dados do EC via URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 8
 testRunner.Then("sou direcionado para a tela de Alteração de Dados Do EC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2- Validar_Acesso_Alteração_do_EC(Via Botão)")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _2_Validar_Acesso_Alteracao_Do_ECViaBotao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2- Validar_Acesso_Alteração_do_EC(Via Botão)", new string[] {
                        "web"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("que faço o login com EC Com Cadastro do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 13
 testRunner.When("acesso a tela de Alteração de Dados do EC via Botão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 14
 testRunner.Then("sou direcionado para a tela de Alteração de Dados Do EC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3- Validar_Redirecionamento_Tela_Cadastro_do_EC(Via URL)")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _3_Validar_Redirecionamento_Tela_Cadastro_Do_ECViaURL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3- Validar_Redirecionamento_Tela_Cadastro_do_EC(Via URL)", new string[] {
                        "web"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("que faço o login com EC Sem Cadastro do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 19
 testRunner.When("acesso a tela de Alteração de Dados do EC via URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 20
 testRunner.Then("sou direcionado para a tela de cadastro de EC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4- Validar_Redirecionamento_Tela_Alteração_do_EC(Via URL)")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _4_Validar_Redirecionamento_Tela_Alteracao_Do_ECViaURL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4- Validar_Redirecionamento_Tela_Alteração_do_EC(Via URL)", new string[] {
                        "web"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("que faço o login com EC Com Cadastro do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 25
 testRunner.When("acesso a tela de Cadastro de Dados do EC via URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 26
 testRunner.Then("sou direcionado para a tela de Alteração de Dados Do EC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("5-Alterar_Dados_do_EC(Validar_Campos_Obrigatórios)")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _5_Alterar_Dados_Do_ECValidar_Campos_Obrigatorios()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5-Alterar_Dados_do_EC(Validar_Campos_Obrigatórios)", new string[] {
                        "web"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("que faço o login com EC Com Cadastro do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 32
 testRunner.And("acesso a tela de Alteração de Dados do EC via URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 33
 testRunner.And("sou direcionado para a tela de Alteração de Dados Do EC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 34
 testRunner.And("limpo os campos obrigatórios", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 35
 testRunner.When("pressiono botão Salvar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 36
 testRunner.Then("visualizo mensagem de Campos Obrigatórios (Tela de Alteração)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("6-Alterar_Dados_EC(Mensagem_Confirmação)")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _6_Alterar_Dados_ECMensagem_Confirmacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("6-Alterar_Dados_EC(Mensagem_Confirmação)", new string[] {
                        "web"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("que faço o login com EC Com Cadastro do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 41
 testRunner.And("acesso a tela de Alteração de Dados do EC via URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 42
 testRunner.And("atualizo os dados do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 43
 testRunner.When("pressiono botão Salvar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 44
 testRunner.Then("visualizo a Mensagem de Confirmacao (Alteração EC)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("7-Alterar_Dados_EC(Alteração_Com_Sucesso)")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _7_Alterar_Dados_ECAlteracao_Com_Sucesso()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("7-Alterar_Dados_EC(Alteração_Com_Sucesso)", new string[] {
                        "web"});
#line 48
this.ScenarioSetup(scenarioInfo);
#line 49
 testRunner.Given("que faço o login com EC Com Cadastro do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 50
 testRunner.And("acesso a tela de Alteração de Dados do EC via URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 51
 testRunner.And("atualizo os dados do Estabelecimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 52
 testRunner.And("pressiono botão Salvar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 53
 testRunner.When("acesso a tela de Alteração de Dados do EC via URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 54
 testRunner.Then("visualizo dados do EC Alterados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
