// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomacaoCuponagem.Features.PortalCuponagem
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Cuponagem_Legado_Criar_Promo")]
    public partial class Cuponagem_Legado_Criar_PromoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LegadoCadastrarPromo.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Cuponagem_Legado_Criar_Promo", "\tEsta Funcionalidade Valida o Cadastro de Promoção - Entrega 1", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1- Cadastro de Promoção - Porcentagem")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("ABC", "01010001", "123", "bloco b", "Executivo", "Brasileiro", "1", null)]
        public virtual void _1_CadastroDePromocao_Porcentagem(string nomeFantasia, string cep, string numero, string complemento, string tipoEstabelecimento, string tipoCozinha, string percentual, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1- Cadastro de Promoção - Porcentagem", @__tags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("que estou na tela de Criar Promoção", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 8
 testRunner.And(string.Format("preencho os dados do Estabelecimento {0}, {1}, {2}, {3}, <tipoEtabelecimento>, {4" +
                        "}", nomeFantasia, cep, numero, complemento, tipoCozinha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
 testRunner.And("pressiono botão Proximo Passo (Estabelecimento)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 10
 testRunner.And(string.Format("preencho os dados da Promocao (Porcentagem) {0}", percentual), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
 testRunner.And("pressiono botão Proximo Passo (Promocao)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
 testRunner.And(string.Format("visualizo dados para confirmacao {0}, {1}, {2}", nomeFantasia, tipoEstabelecimento, tipoCozinha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
 testRunner.When("pressiono botão Criar Promocao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 14
 testRunner.Then("visualizo a Mensagem de Confirmacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2- Cadastro de Promoção - Valor")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("EFC", "02020020", "345", "bloco c", "Executivo", "Brasileiro", "1", null)]
        public virtual void _2_CadastroDePromocao_Valor(string nomeFantasia, string cep, string numero, string complemento, string tipoEstabelecimento, string tipoCozinha, string valor, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2- Cadastro de Promoção - Valor", @__tags);
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("que estou na tela de Criar Promoção", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 22
 testRunner.And(string.Format("preencho os dados do Estabelecimento {0}, {1}, {2}, {3}, <tipoEtabelecimento>, {4" +
                        "}", nomeFantasia, cep, numero, complemento, tipoCozinha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 23
 testRunner.And("pressiono botão Proximo Passo (Estabelecimento)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 24
 testRunner.And(string.Format("preencho os dados da Promocao (Valor) {0}", valor), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 25
 testRunner.And("pressiono botão Proximo Passo (Promocao)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 26
 testRunner.And(string.Format("visualizo dados para confirmacao {0}, {1}, {2}", nomeFantasia, tipoEstabelecimento, tipoCozinha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 27
 testRunner.When("pressiono botão Criar Promocao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 28
 testRunner.Then("visualizo a Mensagem de Confirmacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3- Cadastro de Promoção - Brinde")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("WYZ", "03030030", "679", "bloco J", "Executivo", "Brasileiro", "cafe", null)]
        public virtual void _3_CadastroDePromocao_Brinde(string nomeFantasia, string cep, string numero, string complemento, string tipoEstabelecimento, string tipoCozinha, string brinde, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3- Cadastro de Promoção - Brinde", @__tags);
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
testRunner.Given("que estou na tela de Criar Promoção", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 36
 testRunner.And(string.Format("preencho os dados do Estabelecimento {0}, {1}, {2}, {3}, <tipoEtabelecimento>, {4" +
                        "}", nomeFantasia, cep, numero, complemento, tipoCozinha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 37
 testRunner.And("pressiono botão Proximo Passo (Estabelecimento)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 38
 testRunner.And(string.Format("preencho os dados da Promocao (Brinde) {0}", brinde), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 39
 testRunner.And("pressiono botão Proximo Passo (Promocao)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 40
 testRunner.And(string.Format("visualizo dados para confirmacao {0}, {1}, {2}", nomeFantasia, tipoEstabelecimento, tipoCozinha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 41
 testRunner.When("pressiono botão Criar Promocao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 42
 testRunner.Then("visualizo a Mensagem de Confirmacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
