// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomacaoCuponagem.Features.Connecter
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Connecter_Cancelar Campanha")]
    public partial class Connecter_CancelarCampanhaFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CancelarCampanha.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Connecter_Cancelar Campanha", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1-Cancelar_Campanha - Botão Voltar")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("Restaurante XYZ", "10541663000177", "Lanches", "Brasileiro", "Percentual", "11", null)]
        public virtual void _1_Cancelar_Campanha_BotaoVoltar(string nomeFantasia, string cnpjCentral, string tipoRestaurante, string tipoCozinha, string tipoPromocao, string valorPromocao, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1-Cancelar_Campanha - Botão Voltar", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("visualizo a tela Painel de Campanhas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 8
 testRunner.And(string.Format("crio uma Campanha para Cancelamento {0}, {1}, {2}, {3}, {4}, {5}", nomeFantasia, cnpjCentral, tipoRestaurante, tipoCozinha, tipoPromocao, valorPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
 testRunner.And(string.Format("visualizo uma Campanha Ativa {0}, {1}", nomeFantasia, valorPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 10
 testRunner.And("acesso Detalhe da Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
 testRunner.And(string.Format("visualizo os Detalhes da Campanha {0}", nomeFantasia), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
 testRunner.And("pressiono Botao Cancelar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
 testRunner.And("visualizo Mensagem de Confirmacao de Cancelamento de Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
 testRunner.When("pressiono Botao Voltar(Campanha)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 15
 testRunner.Then("visualizo os Detalhes da Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 16
 testRunner.And("visualizo Detalhe da Campanha Ativa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1-Cancelar_Campanha")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("Restaurante XYZ", "10541663000177", "Lanches", "Brasileiro", "Percentual", "11", null)]
        public virtual void _1_Cancelar_Campanha(string nomeFantasia, string cnpjCentral, string tipoRestaurante, string tipoCozinha, string tipoPromocao, string valorPromocao, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1-Cancelar_Campanha", @__tags);
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("visualizo a tela Painel de Campanhas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 24
 testRunner.And(string.Format("crio uma Campanha para Cancelamento {0}, {1}, {2}, {3}, {4}, {5}", nomeFantasia, cnpjCentral, tipoRestaurante, tipoCozinha, tipoPromocao, valorPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 25
 testRunner.And(string.Format("visualizo uma Campanha Ativa {0}, {1}", nomeFantasia, valorPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 26
 testRunner.And("acesso Detalhe da Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 27
 testRunner.And(string.Format("visualizo os Detalhes da Campanha {0}", nomeFantasia), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 28
 testRunner.And("pressiono Botao Cancelar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 29
 testRunner.And("visualizo Mensagem de Confirmacao de Cancelamento de Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 30
 testRunner.When("pressiono Botao Confirmar(Campanha)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 31
 testRunner.Then("Mensagem de Cancelamento de Campanha Com Sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 32
 testRunner.And("visualizo Detalhe da Campanha Cancelada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
