// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomacaoCuponagem.Features.Connecter
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Connecter_Criar Campanha Connecter")]
    public partial class Connecter_CriarCampanhaConnecterFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CriarCampanha.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Connecter_Criar Campanha Connecter", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1-Criar_Promocao_Porcentagem_No_Connecter")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("Restaurante XYZ", "10541663000177", "Lanches", "Brasileiro", "Percentual", "11", null)]
        public virtual void _1_Criar_Promocao_Porcentagem_No_Connecter(string nomeFantasia, string cnpjCentral, string tipoRestaurante, string tipoCozinha, string tipoPromocao, string valorPromocao, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1-Criar_Promocao_Porcentagem_No_Connecter", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("visualizo a tela Tela de Lista de Campanhas No Connecter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 7
 testRunner.And("pressiono no botão Criar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 8
 testRunner.And("visualizo a tela de Criar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
 testRunner.And(string.Format("preencho os dados do Solicitante(Porcentagem) {0}, {1}, {2}, {3}, {4}, {5}", nomeFantasia, cnpjCentral, tipoRestaurante, tipoCozinha, tipoPromocao, valorPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 10
 testRunner.And("realizo a importação das Lojas Participantes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
 testRunner.And("realizo a importação dos CPFs Impactados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
 testRunner.And("realizo a importação da Arte da Promoção", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
 testRunner.When("pressiono botão Confirmar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 14
 testRunner.Then("visualizo a Mensagem de Confirmacao(Connecter)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 15
 testRunner.And(string.Format("Cupom de Porcentagem Criado no Connecter {0}, {1}", nomeFantasia, valorPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2-Criar_Promocao_Valor_No_Connecter")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("Restaurante do Pedro", "10541663000188", "Prato Feito", "Nordestino", "Dinheiro", "22", null)]
        public virtual void _2_Criar_Promocao_Valor_No_Connecter(string nomeFantasia, string cnpjCentral, string tipoRestaurante, string tipoCozinha, string tipoPromocao, string valorPromocao, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2-Criar_Promocao_Valor_No_Connecter", @__tags);
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("visualizo a tela Tela de Lista de Campanhas No Connecter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 23
 testRunner.And("pressiono no botão Criar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 24
 testRunner.And("visualizo a tela de Criar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 25
 testRunner.And(string.Format("preencho os dados do Solicitante(Valor) {0}, {1}, {2}, {3}, {4}, {5}", nomeFantasia, cnpjCentral, tipoRestaurante, tipoCozinha, tipoPromocao, valorPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 26
 testRunner.And("realizo a importação das Lojas Participantes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 27
 testRunner.And("realizo a importação dos CPFs Impactados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 28
 testRunner.And("realizo a importação da Arte da Promoção", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 29
 testRunner.When("pressiono botão Confirmar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 30
 testRunner.Then("visualizo a Mensagem de Confirmacao(Connecter)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 31
 testRunner.And(string.Format("Cupom de Desconto - Valor Criado no Connecter {0}, {1}", nomeFantasia, valorPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3-Criar_Promocao_Brinde_No_Connecter")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("Restaurante Azulão", "10541663000188", "Lanches", "Brasileiro", "Brinde", null)]
        public virtual void _3_Criar_Promocao_Brinde_No_Connecter(string nomeFantasia, string cnpjCentral, string tipoRestaurante, string tipoCozinha, string tipoPromocao, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3-Criar_Promocao_Brinde_No_Connecter", @__tags);
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("visualizo a tela Tela de Lista de Campanhas No Connecter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 39
 testRunner.And("pressiono no botão Criar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 40
 testRunner.And("visualizo a tela de Criar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 41
 testRunner.And(string.Format("preencho os dados do Solicitante(Brinde) {0}, {1}, {2}, {3}, {4}", nomeFantasia, cnpjCentral, tipoRestaurante, tipoCozinha, tipoPromocao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 42
 testRunner.And("realizo a importação das Lojas Participantes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 43
 testRunner.And("realizo a importação dos CPFs Impactados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 44
 testRunner.And("realizo a importação da Arte da Promoção", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 45
 testRunner.When("pressiono botão Confirmar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 46
 testRunner.Then("visualizo a Mensagem de Confirmacao(Connecter)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 47
 testRunner.And(string.Format("Cupom de Brinde Criado no Connecter {0}", nomeFantasia), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4-Criar_Promocao_Campos_Obrigatorios")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _4_Criar_Promocao_Campos_Obrigatorios()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4-Criar_Promocao_Campos_Obrigatorios", new string[] {
                        "web"});
#line 53
this.ScenarioSetup(scenarioInfo);
#line 54
 testRunner.Given("visualizo a tela Tela de Lista de Campanhas No Connecter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 55
 testRunner.And("pressiono no botão Criar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 56
 testRunner.And("visualizo a tela de Criar Campanha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 57
 testRunner.And("realizo a importação das Lojas Participantes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 58
 testRunner.And("realizo a importação dos CPFs Impactados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 59
 testRunner.And("realizo a importação da Arte da Promoção", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 60
 testRunner.When("pressiono botão Confirmar Campanha(Desabilidado)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 61
 testRunner.Then("visualizo Campos Dados do Solicitante Sem Preenchimento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
